server:
  port: 8080
spring:
  application:
    name: delivery-tracking
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8085/oauth2/jwks
      client:
        registration:
          artificer-client:
            client-id: artificer
            client-secret: 123456
            authorization-grant-type: client_credentials
            scope:
              - couriers:read
              - couriers:write
              - deliveries:read
              - deliveries:write
            client-name: artificer-client
        provider:
          artificer-client:
            token-uri: http://localhost:8085/oauth2/token
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/deliverydb
    username: postgres
    password: postgres
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping:
          delivery-placed-event: com.artificer.artifcerdelivery.delivery.tracking.domain.event.DeliveryPlacedEvent;
          delivery-picked-up-event: com.artificer.artifcerdelivery.delivery.tracking.domain.event.DeliveryPickedUpEvent;
          delivery-fulfilled-event: com.artificer.artifcerdelivery.delivery.tracking.domain.event.DeliveryFulfilledEvent;
eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${random.value}
    prefer-ip-address: true

resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 2
        waitDuration: 20ms
    instances:
      Retry_CourierApiClient_payoutCalculation:
        baseConfig: default
        maxAttempts: 3
        retryExceptions:
          - org.springframework.web.client.ResourceAccessException
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000
    instances:
      CircuitBreaker_CourierApiClient_payoutCalculation:
        baseConfig: default
        waitDurationInOpenState: 5000