server.port: 8081

spring:
  application:
    name: courier-management
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/courierbd
    username: postgres
    password: postgres
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: courier-management
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: '*'
        spring.json.type.mapping:
          delivery-placed-event: com.algadelivery.courier.management.domain.event.DeliveryPlacedIntegrationEvent
          delivery-picked-up-event: com.fasterxml.jackson.databind.JsonNode
          delivery-fulfilled-event: com.algadelivery.courier.management.domain.event.DeliveryFulfilledIntegrationEvent
eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${random.value}
    prefer-ip-address: true